<script setup>
import { computed, onMounted, ref } from 'vue'
import { getTeacherReport, getTeacherReports } from '../api/client'
const items = ref([]); const selected = ref(null); const report = ref(null); const loading = ref(true); const error = ref(''); const filter = ref('all')
const visible = computed(() => items.value.filter(item => filter.value === 'all' || item.kind === filter.value))
function formatDate(value) { return value ? new Intl.DateTimeFormat('zh-HK', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '未记录时间' }
async function open(item) { selected.value = item; report.value = null; try { report.value = await getTeacherReport(item.kind, item.id) } catch (e) { error.value = e.message } }
async function load() { loading.value = true; try { items.value = await getTeacherReports(); if (visible.value[0]) await open(visible.value[0]) } catch (e) { error.value = e.message } finally { loading.value = false } }
onMounted(load)
</script>
<template><main class="app-shell"><header class="topbar"><div><RouterLink class="back-link-inline" to="/teacher">← 返回老师工作台</RouterLink><p class="eyebrow">REPORTS</p><h1>习题统计</h1><p class="muted">课堂按学生去重；练习按每位学生最后完成轮次统计。</p></div></header><p v-if="loading" class="loading-state">正在读取统计…</p><p v-else-if="error" class="error-message">{{ error }}</p><section v-else class="reports-layout"><div class="report-tabs"><button class="choice-card" :class="{ active: filter === 'all' }" @click="filter = 'all'">全部</button><button class="choice-card" :class="{ active: filter === 'classroom' }" @click="filter = 'classroom'">课堂</button><button class="choice-card" :class="{ active: filter === 'practice' }" @click="filter = 'practice'">练习</button><button class="secondary-button" @click="load">重新整理</button></div><div class="reports-layout-inner"><aside class="report-sessions"><button v-for="item in visible" :key="`${item.kind}-${item.id}`" class="choice-row" :class="{ active: selected?.id === item.id }" @click="open(item)"><span>{{ item.title }}<small>{{ item.subtitle }}</small><small>{{ formatDate(item.created_at) }}</small></span></button><p v-if="!visible.length" class="empty-state">暂无统计记录。</p></aside><section class="report-panel"><template v-if="report"><div class="report-context"><strong>{{ report.title }}</strong><span>参与人数：{{ report.participant_count }}</span></div><article v-for="question in report.questions" :key="question.id" class="report-question"><div class="report-question-heading"><div><span class="question-number">{{ question.sort_order }}</span><strong>{{ question.question_type === 'single_choice' ? '选择题' : '非选择题' }}</strong></div><span>正确率 {{ question.accuracy }}%</span></div><p class="correct-answer">正确答案：<strong>{{ question.correct_option || '不判分' }}</strong></p><div class="report-bars"><div v-for="key in ['A','B','C','D']" :key="key" class="report-bar"><span>{{ key }}</span><div><i :style="{ width: `${question.submitted_count ? question.distribution[key] / question.submitted_count * 100 : 0}%` }"></i></div><b>{{ question.distribution[key] }}</b></div></div><p class="helper-text">已作答 {{ question.submitted_count }} 人，答对 {{ question.correct_count }} 人</p></article></template><p v-else class="empty-state">请选择一项统计。</p></section></div></section></main></template>
