<script setup>
import { computed, onMounted, ref } from 'vue'
import { getSessions, getSessionReport, archiveSession } from '../api/client'
const sessions = ref([]); const selected = ref(null); const report = ref(null); const loading = ref(true); const reportLoading = ref(false); const archiving = ref(false); const errorMessage = ref(''); const page = ref(1); const pageSize = 5
const closedSessions = computed(() => sessions.value.filter(item => item.status === 'closed'))
const pageCount = computed(() => Math.max(1, Math.ceil(closedSessions.value.length / pageSize)))
const pageSessions = computed(() => closedSessions.value.slice((page.value - 1) * pageSize, page.value * pageSize))
function formatDate(value) { return value ? new Intl.DateTimeFormat('zh-HK', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '未记录时间' }
function accuracyClass(value) { return value >= 80 ? 'accuracy-good' : value >= 50 ? 'accuracy-medium' : 'accuracy-low' }
async function openReport(session) { reportLoading.value = true; errorMessage.value = ''; selected.value = session; report.value = null; try { report.value = await getSessionReport(session.id) } catch (e) { errorMessage.value = e.message } finally { reportLoading.value = false } }
async function archiveSelected(session) { if (!window.confirm('确定要归档这场已结束的课堂吗？统计数据会保留，但默认列表将不再显示。')) return; archiving.value = true; try { await archiveSession(session.id); sessions.value = sessions.value.filter(item => item.id !== session.id); report.value = null; selected.value = null; if (page.value > pageCount.value) page.value = pageCount.value; if (pageSessions.value[0]) await openReport(pageSessions.value[0]) } catch (e) { errorMessage.value = e.message } finally { archiving.value = false } }
function changePage(nextPage) { page.value = Math.min(pageCount.value, Math.max(1, nextPage)); if (pageSessions.value[0]) openReport(pageSessions.value[0]) }
onMounted(async () => { try { sessions.value = await getSessions(); if (pageSessions.value[0]) await openReport(pageSessions.value[0]) } catch (e) { errorMessage.value = e.message } finally { loading.value = false } })
</script>
<template><main class="app-shell"><header class="topbar"><div><RouterLink class="back-link-inline" to="/teacher">← 返回老师工作台</RouterLink><p class="eyebrow">LIVE REPORTS</p><h1>即时统计</h1><p class="muted">只显示已结束的课堂，查看学生提交分布和正确情况。</p></div></header><p v-if="loading" class="loading-state">正在读取课堂列表…</p><p v-else-if="errorMessage && !reportLoading" class="error-message">{{ errorMessage }}</p><section v-else class="reports-layout"><aside class="report-sessions"><h2>课堂场次</h2><button v-for="item in pageSessions" :key="item.id" :class="{ active: selected?.id === item.id }" class="choice-row" @click="openReport(item)"><span>{{ item.question_sets?.name || '题目集合' }}<small>{{ item.classes?.name || item.classes?.code || '' }}</small><small>结束时间：{{ formatDate(item.closed_at) }}</small></span></button><p v-if="!closedSessions.length" class="empty-state">目前还没有已结束的课堂场次。</p><div v-else class="pagination"><button class="secondary-button" :disabled="page <= 1" @click="changePage(page - 1)">上一页</button><span>第 {{ page }} / {{ pageCount }} 页</span><button class="secondary-button" :disabled="page >= pageCount" @click="changePage(page + 1)">下一页</button></div></aside><section class="report-panel"><p v-if="reportLoading" class="loading-state">正在读取这一场课堂的统计…</p><template v-else-if="report"><div class="report-context"><strong>{{ report.session.question_sets?.name || '题目集合' }}</strong><span>{{ report.session.classes?.name || report.session.classes?.code || '' }}</span><span>结束时间：{{ formatDate(report.session.closed_at) }}</span><button class="secondary-button archive-button" :disabled="archiving" @click="archiveSelected(selected)">{{ archiving ? '归档中…' : '归档这场课堂' }}</button></div><div class="report-summary"><span>已加入 <strong>{{ report.participant_count }}</strong> 台设备</span><span>总提交 <strong>{{ report.total_submitted_count }}</strong> 次</span></div><article v-for="question in report.questions" :key="question.id" class="report-question"><div class="report-question-heading"><div><span class="question-number">{{ question.sort_order }}</span><strong>{{ question.question_text || '图片题目' }}</strong></div><span :class="accuracyClass(question.accuracy)">正确率 {{ question.accuracy }}%</span></div><p class="correct-answer">正确答案：<strong>{{ question.correct_option_key || '未设置' }}</strong></p><div class="report-bars"><div v-for="key in ['A','B','C','D']" :key="key" class="report-bar"><span>{{ key }}</span><div><i :style="{ width: `${question.submitted_count ? question.distribution[key] / question.submitted_count * 100 : 0}%` }"></i></div><b>{{ question.distribution[key] }}</b></div></div><p class="helper-text">已提交 {{ question.submitted_count }} 人，答对 {{ question.correct_count }} 人</p></article></template><p v-else class="empty-state">请选择一场已结束的课堂。</p></section></section></main></template>
