<script setup>
import { computed, onMounted, ref } from 'vue'
import QRCode from 'qrcode'
import { createSession, getClasses, getQuestionSets } from '../api/client'

const classes = ref([]); const questionSets = ref([]); const selectedGrade = ref(''); const selectedClass = ref(''); const selectedSet = ref('')
const session = ref(null); const qrDataUrl = ref(''); const loading = ref(true); const saving = ref(false); const errorMessage = ref('')
const grades = computed(() => [...new Map(classes.value.map(item => [item.grade_id, item.grades || { name: item.grade_id }])).entries()].map(([id, data]) => ({ id, ...data })))
const filteredClasses = computed(() => classes.value.filter(item => item.grade_id === selectedGrade.value))
const selectedClassName = computed(() => filteredClasses.value.find(item => item.id === selectedClass.value)?.name || '')
onMounted(async () => { try { const [allClasses, allSets] = await Promise.all([getClasses(), getQuestionSets()]); classes.value = allClasses; questionSets.value = allSets.filter(item => item.status === 'published'); selectedGrade.value = grades.value[0]?.id || ''; selectedClass.value = filteredClasses.value[0]?.id || ''; selectedSet.value = questionSets.value[0]?.id || '' } catch (e) { errorMessage.value = e.message } finally { loading.value = false } })
function chooseGrade(id) { selectedGrade.value = id; selectedClass.value = filteredClasses.value[0]?.id || '' }
async function submit() { saving.value = true; errorMessage.value = ''; try { session.value = await createSession({ question_set_id: selectedSet.value, class_id: selectedClass.value }); qrDataUrl.value = await QRCode.toDataURL(session.value.join_url, { width: 300, margin: 2 }) } catch (e) { errorMessage.value = e.message } finally { saving.value = false } }
</script>
<template><main class="app-shell"><header class="topbar"><div><RouterLink class="back-link-inline" to="/teacher">← 返回老师工作台</RouterLink><p class="eyebrow">CLASSROOM SESSION</p><h1>课堂场次</h1><p class="muted">先选择年级和班级，再选择已发布的题目集合。</p></div></header><p v-if="loading" class="loading-state">正在读取资料…</p><p v-else-if="errorMessage" class="error-message">{{ errorMessage }}</p><section v-else class="detail-panel session-create-panel"><div class="selection-block"><h2>1. 选择年级</h2><div class="choice-grid grade-grid"><button v-for="grade in grades" :key="grade.id" :class="{ active: selectedGrade === grade.id }" class="choice-card" @click="chooseGrade(grade.id)">{{ grade.name }}</button></div></div><div class="selection-block"><h2>2. 选择班级</h2><div class="choice-grid"><button v-for="item in filteredClasses" :key="item.id" :class="{ active: selectedClass === item.id }" class="choice-card" @click="selectedClass = item.id">{{ item.name || item.code }}</button></div><p v-if="selectedClass" class="helper-text">已选择：{{ selectedClassName }}</p></div><div class="selection-block"><h2>3. 选择题目集合</h2><div class="choice-list"><button v-for="item in questionSets" :key="item.id" :class="{ active: selectedSet === item.id }" class="choice-row" @click="selectedSet = item.id"><span>{{ item.name }}</span><small>{{ item.question_count }} 题</small></button></div><p v-if="!questionSets.length" class="empty-state">目前没有已发布的题目集合，请先到题目管理发布。</p></div><button class="primary-button" :disabled="saving || !selectedClass || !selectedSet" @click="submit">{{ saving ? '建立中…' : '建立课堂并生成二维码' }}</button><div v-if="session" class="session-created"><img :src="qrDataUrl" alt="课堂二维码" class="qr-code"><p class="success-message">课堂已建立，共 {{ session.question_count }} 题</p><p class="helper-text">请让学生扫描此二维码：<br><a :href="session.join_url" target="_blank">{{ session.join_url }}</a></p><RouterLink class="primary-button inline-button" :to="`/teacher/sessions/${session.id}`">进入课堂控制台</RouterLink></div></section></main></template>
