<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { answerClassroom, getClassroom, joinClassroom } from '../api/client'
const route = useRoute(); const token = String(route.params.token); const state = ref(null); const selected = ref(''); const error = ref(''); const now = ref(Date.now()); let timer; let clock
const remaining = computed(() => { const deadline = state.value?.deadline_at; return deadline ? Math.max(0, Math.ceil((Date.parse(deadline) - now.value) / 1000)) : null })
async function load() { try { state.value = await getClassroom(token); if (state.value.status !== 'closed') await joinClassroom(token); error.value = '' } catch (e) { if (!state.value) error.value = e.message } }
async function submit(letter) { if (!state.value?.question || state.value.question_status !== 'open') return; try { await answerClassroom(token, { question_id: state.value.question.id, selected_option: letter }); selected.value = letter } catch (e) { error.value = e.message } }
onMounted(async () => { await load(); timer = setInterval(load, 2000); clock = setInterval(() => { now.value = Date.now() }, 250) }); onUnmounted(() => { clearInterval(timer); clearInterval(clock) })
</script>
<template><main class="auth-shell"><section class="auth-card student-card student-session-card"><div class="brand-mark student-mark">答</div><p class="eyebrow">ENGLISH MATH CLASSROOM</p><h1>课堂答题</h1><p v-if="error" class="error-message">{{ error }}</p><p v-else-if="!state" class="loading-state">正在连接课堂…</p><template v-else-if="state.status === 'waiting'"><p class="participant-count">已进入课堂：{{ state.participant_count || 0 }} 人</p><p class="muted">等待老师开始。</p></template><template v-else-if="state.status === 'active' && state.question_status === 'open' && state.question"><p v-if="remaining !== null" class="countdown" :class="{ urgent: remaining <= 5 }">剩余 {{ remaining }} 秒</p><img :src="state.question.image_url" class="question-image" alt="题目图片"><div class="student-options fixed-options"><button v-for="letter in ['A','B','C','D']" :key="letter" :class="{ selected: selected === letter }" @click="submit(letter)">{{ letter }}</button></div><p class="muted">课堂中暂不显示对错，由老师统一讲解。</p></template><template v-else><p class="muted">课堂已结束。</p></template></section></main></template>
