<script setup>
import { onMounted, onUnmounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { getPublicSession, joinPublicSession, submitPublicAnswer } from '../api/client'
const route = useRoute(); const token = route.params.token; const state = ref(null); const selected = ref(''); const selectedQuestionId = ref(''); const joined = ref(false); const errorMessage = ref(''); let timer; let loading = false
const browserKey = (() => { const key = localStorage.getItem('hhx_browser_key'); if (key) return key; const next = crypto.randomUUID(); localStorage.setItem('hhx_browser_key', next); return next })()
async function load() { if (loading) return; loading = true; try { const nextState = await getPublicSession(token); if (nextState?.question?.id !== selectedQuestionId.value) { selected.value = ''; selectedQuestionId.value = nextState?.question?.id || '' } state.value = nextState; errorMessage.value = ''; if (state.value?.status === 'closed') clearInterval(timer); else if (!joined.value) { await joinPublicSession(token, browserKey); joined.value = true } } catch (e) { if (!state.value) errorMessage.value = e.message } finally { loading = false } }
async function answer(option) { if (!state.value?.question) return; errorMessage.value = ''; try { await submitPublicAnswer(token, { browser_key: browserKey, question_id: state.value.question.id, selected_option_id: option.id }); selected.value = option.id; selectedQuestionId.value = state.value.question.id } catch (e) { errorMessage.value = e.message } }
onMounted(async () => { await load(); if (state.value?.status !== 'closed') timer = setInterval(load, 2000) }); onUnmounted(() => clearInterval(timer))
</script>
<template><main class="auth-shell ui-v2-shell"><a-card class="auth-card student-card ui-v2-card" :bordered="false"><div class="brand-mark student-mark">答</div><p class="eyebrow">ENGLISH MATH CLASSROOM</p><h1>课堂答题</h1><a-alert v-if="errorMessage" type="error" show-icon>{{ errorMessage }}</a-alert><a-skeleton v-else-if="!state" :animation="true" :rows="3" /><template v-else-if="state.status !== 'active' && state.status !== 'closed'"><a-statistic title="目前进入课堂" :value="state.participant_count || 0" suffix="台设备" /><p class="muted">老师进入课堂控制台后会自动开始答题。</p></template><template v-else-if="state.status === 'active' && state.question && state.current_question_status === 'open'"><p class="muted">请选择答案，提交后仍可修改。</p><h2 class="student-question">{{ state.question.question_text }}</h2><div class="student-options"><a-button v-for="option in state.question.options" :key="option.id" :type="selected === option.id ? 'primary' : 'outline'" long @click="answer(option)">{{ option.option_key }}. {{ option.option_text }}</a-button></div><a-alert :type="selected ? 'success' : 'warning'" show-icon>{{ selected ? '答案已提交' : '待学生作答' }}</a-alert></template><template v-else-if="state.status === 'active' && state.current_question_status === 'locked'"><a-alert type="warning" show-icon>当前题目已锁定，等待老师进入下一题。</a-alert></template><template v-else><a-result status="success" title="课堂测试已完成" /></template></a-card></main></template>
