<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { completeStudentPractice, getStudentQuestionSet, startStudentPractice, submitStudentPracticeAnswer } from '../api/client'

const route = useRoute(); const router = useRouter(); const setId = route.params.id
const data = ref(null); const attemptId = ref(''); const index = ref(0); const selected = ref(''); const result = ref(null); const loading = ref(true); const busy = ref(false); const errorMessage = ref('')
const browserKey = (() => { const existing = localStorage.getItem('hhx_browser_key'); if (existing) return existing; const value = crypto.randomUUID(); localStorage.setItem('hhx_browser_key', value); return value })()
const question = computed(() => data.value?.questions?.[index.value]); const isLast = computed(() => Boolean(data.value && index.value === data.value.questions.length - 1))
async function load() { try { data.value = await getStudentQuestionSet(setId); const started = await startStudentPractice(setId, browserKey); attemptId.value = started.attempt_id } catch (e) { errorMessage.value = e.message } finally { loading.value = false } }
async function choose(option) { if (busy.value || !question.value) return; busy.value = true; try { await submitStudentPracticeAnswer(setId, { browser_key: browserKey, attempt_id: attemptId.value, question_id: question.value.id, selected_option_id: option.id }); selected.value = option.id } catch (e) { errorMessage.value = e.message } finally { busy.value = false } }
async function next() { if (!selected.value || busy.value) return; busy.value = true; try { if (isLast.value) result.value = await completeStudentPractice(setId, { browser_key: browserKey, attempt_id: attemptId.value }); else { index.value += 1; selected.value = '' } } catch (e) { errorMessage.value = e.message } finally { busy.value = false } }
onMounted(load)
</script>
<template><main class="auth-shell"><section class="auth-card student-card student-session-card"><RouterLink class="back-link-inline" to="/student">← 返回學生練習</RouterLink><p class="eyebrow">QUESTION PRACTICE</p><h1>{{ data?.name || '題目集合' }}</h1><p v-if="loading" class="loading-state">正在載入題目…</p><p v-else-if="errorMessage" class="error-message">{{ errorMessage }}</p><template v-else-if="result"><div class="completion-message"><h2>練習已完成</h2><p>本次完成 {{ result.answers?.length || 0 }} 題。</p></div><button class="primary-button" @click="router.push('/student')">返回學生練習</button></template><template v-else-if="question"><div class="practice-progress"><span>第 {{ index + 1 }} / {{ data.questions.length }} 題</span></div><img v-if="question.question_image_url" class="question-image" :src="question.question_image_url" alt="題目圖片" /><h2 v-if="question.question_text" class="student-question">{{ question.question_text }}</h2><div class="student-options"><button v-for="option in question.options" :key="option.id" :class="{ selected: selected === option.id }" :disabled="busy" @click="choose(option)"><strong>{{ option.option_key }}.</strong><img v-if="option.option_image_url" class="option-image" :src="option.option_image_url" alt="選項圖片" /><template v-else>{{ option.option_text }}</template></button></div><p :class="selected ? 'success-message' : 'pending-message'">{{ selected ? '答案已提交' : '待學生作答' }}</p><button class="primary-button practice-next-button" :disabled="!selected || busy" @click="next">{{ busy ? '處理中…' : (isLast ? '完成練習' : '下一題') }}</button></template></section></main></template>
