<script setup>
import { onMounted, ref } from 'vue'
import { getTeacherGrades, getTeacherWords, importWords, previewWords } from '../api/client'
const grades = ref([]); const batches = ref([]); const gradeId = ref(''); const file = ref(null); const preview = ref(null); const busy = ref(false); const message = ref(''); const error = ref('')
onMounted(async () => { try { const [rows, published] = await Promise.all([getTeacherGrades(), getTeacherWords()]); grades.value = rows; batches.value = published; gradeId.value = grades.value[0]?.id || '' } catch (e) { error.value = e.message } })
function resetPreview() { preview.value = null; message.value = ''; error.value = '' }
async function chooseFile(event) { file.value = event.target.files?.[0] || null; resetPreview(); if (!file.value || !gradeId.value) return; busy.value = true; try { preview.value = await previewWords(gradeId.value, file.value) } catch (e) { error.value = e.message } finally { busy.value = false } }
function chooseGrade() { file.value = null; resetPreview() }
async function submit() { if (!file.value || !preview.value || !gradeId.value) return; busy.value = true; error.value = ''; message.value = ''; try { const result = await importWords(gradeId.value, file.value); message.value = `已上传单词，共 ${result.word_count} 个。`; batches.value = await getTeacherWords(); file.value = null; preview.value = null } catch (e) { error.value = e.message } finally { busy.value = false } }
</script>
<template><main class="app-shell"><header class="topbar"><div><RouterLink class="back-link-inline" to="/teacher">← 返回老师工作台</RouterLink><p class="eyebrow">VOCABULARY BANK</p><h1>单词词库</h1><p class="muted">按年级覆盖上传；同年级重复单词只保留第一次出现。</p></div></header><section class="detail-panel form-stack"><label><span>年级</span><select v-model="gradeId" @change="chooseGrade"><option v-for="grade in grades" :key="grade.id" :value="grade.id">{{ grade.code }} · {{ grade.name }}</option></select></label><label><span>Excel 文件</span><input type="file" accept=".xlsx" @change="chooseFile"></label><p class="helper-text">表头：单词、词义。选中文件后会先显示预览，确认无误再上传。</p><p v-if="error" class="error-message">{{ error }}</p><p v-if="message" class="success-message">{{ message }}</p><button class="primary-button" :disabled="busy || !preview || !file || !gradeId" @click="submit">{{ busy ? '上传中…' : '上传单词' }}</button></section><section v-if="preview" class="detail-panel word-preview-panel"><div class="panel-heading"><div><p class="eyebrow">UPLOAD PREVIEW</p><h2>单词与词义</h2></div><span class="preview-count">共 {{ preview.word_count }} 个</span></div><div class="word-preview-list"><div v-for="item in preview.words" :key="item.sort_order" class="word-preview-row"><span class="word-preview-index">{{ item.sort_order }}</span><strong>{{ item.word }}</strong><span>{{ item.meaning }}</span></div></div></section><section class="detail-panel word-bank-list"><div class="panel-heading"><div><p class="eyebrow">PUBLISHED BANKS</p><h2>已发布词库</h2></div></div><p v-if="!batches.length" class="empty-state">目前还没有已发布词库。</p><div v-else class="word-bank-rows"><div v-for="batch in batches" :key="batch.id" class="word-bank-row"><strong>{{ batch.grades?.code }} · {{ batch.grades?.name }}</strong><span>{{ batch.word_count }} 个单词</span></div></div></section></main></template>
