<script setup>
import { onMounted, onUnmounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { getSessions, getPublicSession, getSessionStats, lockSession, nextSession } from '../api/client'
const route = useRoute(); const session = ref(null); const publicState = ref(null); const stats = ref(null); const errorMessage = ref(''); let timer
async function load() { try { const sessions = await getSessions(); session.value = sessions.find(x => x.id === route.params.id); if (session.value) { publicState.value = await getPublicSession(session.value.access_token); stats.value = await getSessionStats(session.value.id) } } catch (e) { errorMessage.value = e.message } }
async function action(fn) { try { await fn(route.params.id); await load() } catch (e) { errorMessage.value = e.message } }
onMounted(async () => { await load(); timer = setInterval(load, 2500) }); onUnmounted(() => clearInterval(timer))
</script>
<template><main class="app-shell"><header class="topbar"><div><RouterLink class="back-link-inline" to="/teacher">← 返回老师工作台</RouterLink><p class="eyebrow">LIVE CLASSROOM</p><h1>课堂控制台</h1></div></header><p v-if="errorMessage" class="error-message">{{ errorMessage }}</p><section v-if="session" class="detail-panel"><div class="session-status"><span class="status-pill">{{ session.status === 'active' ? '进行中' : session.status === 'closed' ? '已结束' : session.status }}</span><span>已加入 {{ stats?.participant_count || 0 }} 人 · 已提交 {{ stats?.submitted_count || 0 }} 人</span></div><div v-if="publicState?.question" class="live-question"><p class="eyebrow">当前题目 {{ publicState.question.sort_order }}</p><h2>{{ publicState.question.question_text }}</h2><div class="option-preview-grid"><span v-for="option in publicState.question.options" :key="option.id">{{ option.option_key }}. {{ option.option_text }}</span></div></div><div v-else class="completion-message"><h2>所有题目已经播放完毕</h2><p>课堂答题已经结束，请前往「即时统计」查看学生的提交分布和正确情况。</p><RouterLink class="primary-button inline-button" to="/teacher/reports">前往即时统计</RouterLink></div><div v-if="session.status === 'active'" class="distribution"><div v-for="key in ['A','B','C','D']" :key="key"><strong>{{ key }}</strong><span>{{ stats?.distribution?.[key] || 0 }}</span></div></div><div class="button-row"><button v-if="session.status === 'active'" class="secondary-button" @click="action(lockSession)">锁定当前题</button><button v-if="session.status === 'active'" class="primary-button" @click="action(nextSession)">下一题</button></div></section></main></template>
